### ISSUE TITLE
Select All

### ISSUE THREAD

**Issue by mah-shamim** [hafijul233/HackerRank#10]
Query all columns (attributes) for every row in the **CITY** table.

The **CITY** table is described as follows: 

![1449729804-f21d187d0f-CITY](https://user-images.githubusercontent.com/15815972/182688919-15051e5a-d6fb-41e3-b9bd-e9f6f8783b53.jpg)

**Comment by mah-shamim** [comment]
SELECT * FROM CITY;

**Comment by hafijul233** [comment]
accepted
